openapi: 3.0.3 
info:
  title: P2P Connector for Mojaloop APIs
  description: |
    Specification for the Core Connector for Mojaloop API This API can be used by DFSP backends to simplify the process of sending and receiving funds within a Mojaloop scheme. **Note on terminology:** The term "Switch" is equal to the term "Hub", and the term "FSP" is equal to the term "DFSP".
  version: 1.0.0
servers:
- url: /
paths:
  /secured/sendmoney:
    post:
      tags:
      - sendmoney
      summary: Sends money from one account to another
      description: |
        The HTTP request `POST /secured/sendmoney` is used by the Payer DFSP to request the movement of funds from the Payer DFSP to the Payee DFSP. The underlying Mojaloop API has three stages for money transfer:
          1. Party lookup (discovery phase). This facilitates a check by the sending party that the destination party is correct before proceeding with a money movement.
          2. Quotation (agreement phase). This facilitates the exchange of fee information and the construction of a cryptographic "contract" between the Payee and Payer DFSPs before funds are transferred.
          3. Transfer (transfer phase). The enactment of the previously agreed "contract".
        This method has several modes of operation. - If the configuration variable `AUTO_ACCEPT_PARTY` is set to `"false"`, this method will terminate when the Payee party has been resolved and Payee party details have been returned.
          If the Payer wishes to proceed with the transfer, then a subsequent `PUT /secured/sendmoney/{transferId}` request (accepting the Payee party) is required to continue the operation.
          The Payment Manager will then proceed to the quotation stage.
        - If the configuration variable `AUTO_ACCEPT_QUOTES` is set to `"false"`, this method will terminate and return the quotation when it has been received from the Payee DFSP.
          If the Payee wishes to proceed with the transfer, then a subsequent `PUT /secured/sendmoney/{transferId}` request (accepting the quote) is required to continue the operation.
          The Payment Manager will then proceed to the transfer state.
        If the configuration variables `AUTO_ACCEPT_PARTY` and `AUTO_ACCEPT_QUOTES` are both set to `"true"`, this method will block until all three transfer stages are complete. Upon completion, it will return the entire set of transfer details received during the operation. Combinations of settings for `AUTO_ACCEPT...` configuration variables allow the Payment Manager user to decide which mode of operation best suits their use cases. i.e., the Payment Manager can be configured to "break" the three-stage transfer at these points in order to execute backend logic such as party verification, quoted fees assessments, etc.
      operationId: securedPostSendMoney
      parameters:
      - name: Authorization
        in: header
        description: "The `Authorization` header field is used by the API for securely transmitting information in a compact and self-contained manner as a JSON object. The field must be set with a JWT (JSON Web Token) generated using an RSA private key in PKCS#8 format, loaded from a specified file (e.g., private_key.pem), and signed with the RS256 algorithm. Using PKCS#8 format ensures that the private key is stored in a standardized and secure way. The payload must include the necessary claims required by the API. The secure JWT (JSON Web Token) generated from a private key and payload. Once generated, Transaction ID from the DFSP backend, used to reconcile transactions between
    the Switch and the DFSP backend systems. In Mojaloop and PM4ML (SDK + Core Connector),
    this field is mandatory. However, most Core Banking Systems (CBS) generate the
    transaction ID only once the transaction stage is reached. Therefore, during
    the payer integration, the DFSP can provide a UUID in the initial call (e.g., KYC)
    and later override it with the actual transaction ID (homeTransactionId) in the
    subsequent transaction confirmation call.in the Authorization header in the format Authorization: <JWT> to enable secure, authenticated API requests."
        required: true
        schema:
          type: string
          description: Bearer token for authorization
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
      - name: fspiop-source
        in: header
        description: The payer DFSP identifier. For `POST /secured/sendmoney`, this must match `from.fspId` in the request body. For the follow-up `PUT /secured/sendmoney/{transferId}` requests, this must be the same payer DFSP ID used in the initial send money request.
        required: true
        schema:
          type: string
      requestBody:
        description: Transfer request body
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/postSendMoneyRequest'
        required: true
      responses:
        "200":
          $ref: '#/components/responses/postSendMoneySuccess'
        "500":
          $ref: '#/components/responses/postTransferServerError'
  /secured/sendmoney/{transferId}(acceptParty):
    put:
      tags:
      - sendmoney
      summary: Continues a transfer that has paused at the party lookup and/or quote stage in order to accept or reject Payee party and/or quote
      description: |
        The HTTP request `PUT /secured/sendmoney/{transferId}` is used by the Payer DFSP to continue a transfer initiated via the `POST /secured/sendmoney` method that has halted after party lookup and/or quotation stage. The request body should contain `acceptParty` property set to `true` as required to continue the transfer. See the description of the `PUT /secured/sendmoney` HTTP method for more information on modes of transfer.
      operationId: securedPutSendMoneyAcceptPartyByTransferId
      parameters:
      - name: transferId
        in: path
        description: Transfer identifier.
        required: true
        schema:
          pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
          type: string
      - name: Authorization
        in: header
        description: "The `Authorization` header field is used by the API for securely transmitting information in a compact and self-contained manner as a JSON object. The field must be set with a JWT (JSON Web Token) generated using an RSA private key in PKCS#8 format, loaded from a specified file (e.g., private_key.pem), and signed with the RS256 algorithm. Using PKCS#8 format ensures that the private key is stored in a standardized and secure way. The payload must include the necessary claims required by the API. The secure JWT (JSON Web Token) generated from a private key and payload. Once generated, the JWT (the token) should be included in the Authorization header in the format Authorization: <JWT> to enable secure, authenticated API requests."
        required: true
        schema:
          type: string
          description: Bearer token for authorization
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
      - name: fspiop-source
        in: header
        description: The payer DFSP identifier. This must be the same `fspiop-source` value used in the initial `POST /secured/sendmoney` call and must match `from.fspId` from that request body.
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/AcceptPartyRequest'
      responses:
        "200":
          $ref: '#/components/responses/acceptPartySuccess'
        "500":
          $ref: '#/components/responses/putAcceptPartyTransferServerError'
  /secured/sendmoney/{transferId}(acceptQuote):
    put:
      tags:
      - sendmoney
      summary: Continues a transfer that has paused at the party lookup and/or quote stage in order to accept or reject Payee party and/or quote
      description: |
        The HTTP request `PUT /secured/sendmoney/{transferId}` is used by the Payer DFSP to continue a transfer initiated via the `POST /secured/sendmoney` method that has halted after party lookup and/or quotation stage. The request body should contain `acceptQuote` property set to `true` as required to continue the transfer. See the description of the `PUT /secured/sendmoney` HTTP method for more information on modes of transfer.
      operationId: securedPutSendMoneyAcceptQuoteByTransferId
      parameters:
      - name: transferId
        in: path
        description: Transfer identifier.
        required: true
        schema:
          pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
          type: string
      - name: Authorization
        in: header
        description: "The `Authorization` header field is used by the API for securely transmitting information in a compact and self-contained manner as a JSON object. The field must be set with a JWT (JSON Web Token) generated using an RSA private key in PKCS#8 format, loaded from a specified file (e.g., private_key.pem), and signed with the RS256 algorithm. Using PKCS#8 format ensures that the private key is stored in a standardized and secure way. The payload must include the necessary claims required by the API. The secure JWT (JSON Web Token) generated from a private key and payload. Once generated, the JWT (the token) should be included in the Authorization header in the format Authorization: <JWT> to enable secure, authenticated API requests."
        required: true
        schema:
          type: string
          description: Bearer token for authorization
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
      - name: fspiop-source
        in: header
        description: The payer DFSP identifier. This must be the same `fspiop-source` value used in the initial `POST /secured/sendmoney` call and must match `from.fspId` from that request body.
        required: true
        schema:
          type: string
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/acceptQuoteRequest'
      responses:
        "200":
          $ref: '#/components/responses/acceptQuoteSuccess'
        "500":
          $ref: '#/components/responses/putAcceptQuoteTransferServerError'
  /transfers/{transferId}:
    get:
      tags:
      - sendmoney
      summary:  Retrieves the current status and details of a specific transfer.
      description: |
        The `GET /transfers/{transferId}` endpoint returns the current status of a transfer,
        including its state, direction, extensions, and any related error information.
        This allows the client to verify the transfer's progress or final outcome.
      operationId: getTransfersByTransferId
      parameters:
      - name: transferId
        in: path
        description: Transfer identifier.
        required: true
        schema:
          type: string
      responses:
        "200":
          $ref: '#/components/responses/getTransferSuccess'
        "500":
          $ref: '#/components/responses/getTransferError'  
  /dfsp-list-with-prefixes:
    get:
      tags:
      - dfsps
      summary: Retrieves a complete list of registered Digital Financial Service Providers (DFSPs) on the Hub along with their dialing prefixes.
      description: |
          The `GET /dfsp-list-with-prefixes` endpoint retrieves a complete list of
          registered Digital Financial Service Providers (DFSPs) on the Hub,
          including their associated dialing prefixes. 
      responses:
        "200": 
          $ref: '#/components/responses/getDfspPrefixSuccess'
  /dfsp-list-with-prefixes-by-usecase/{usecase}:
    get:
      tags:
      - dfsps
      summary: Retrieves a filtered list of DFSPs based on a specific use case.
      description: |
          The `GET /dfsp-list-with-prefixes/{usecase}` endpoint retrieves a complete list of
          registered Digital Financial Service Providers (DFSPs) on the Hub,
          including their associated dialing prefixes based on a specific usecase.
      parameters:
      - name: usecase
        in: path
        description: specific usecase.
        required: true
        schema:
          type: string
          example: "PERSON_TO_PERSON"
      responses:
        "200": 
          $ref: '#/components/responses/getDfspPrefixSuccess'

components:
  schemas:
    amountType:
      type: string
      description: SEND for send amount. RECEIVE for receive amount.
      enum:
      - SEND
      - RECEIVE
    amount:
     type: string
     pattern: "^([0]|([1-9][0-9]{0,13}))([.][0-9]{0,3}[0-9])?$"
    currency:
      maxLength: 3
      minLength: 3
      type: string
      enum:
      - AED
      - AFN
      - ALL
      - AMD
      - ANG
      - AOA
      - ARS
      - AUD
      - AWG
      - AZN
      - BAM
      - BBD
      - BDT
      - BGN
      - BHD
      - BIF
      - BMD
      - BND
      - BOB
      - BRL
      - BSD
      - BTN
      - BWP
      - BYN
      - BZD
      - CAD
      - CDF
      - CHF
      - CLP
      - CNY
      - COP
      - CRC
      - CUC
      - CUP
      - CVE
      - CZK
      - DJF
      - DKK
      - DOP
      - DZD
      - EGP
      - ERN
      - ETB
      - EUR
      - FJD
      - FKP
      - GBP
      - GEL
      - GGP
      - GHS
      - GIP
      - GMD
      - GNF
      - GTQ
      - GYD
      - HKD
      - HNL
      - HRK
      - HTG
      - HUF
      - IDR
      - ILS
      - IMP
      - INR
      - IQD
      - IRR
      - ISK
      - JEP
      - JMD
      - JOD
      - JPY
      - KES
      - KGS
      - KHR
      - KMF
      - KPW
      - KRW
      - KWD
      - KYD
      - KZT
      - LAK
      - LBP
      - LKR
      - LRD
      - LSL
      - LYD
      - MAD
      - MDL
      - MGA
      - MKD
      - MMK
      - MNT
      - MOP
      - MRO
      - MUR
      - MVR
      - MWK
      - MXN
      - MYR
      - MZN
      - NAD
      - NGN
      - NIO
      - NOK
      - NPR
      - NZD
      - OMR
      - PAB
      - PEN
      - PGK
      - PHP
      - PKR
      - PLN
      - PYG
      - QAR
      - RON
      - RSD
      - RUB
      - RWF
      - SAR
      - SBD
      - SCR
      - SDG
      - SEK
      - SGD
      - SHP
      - SLL
      - SOS
      - SPL
      - SRD
      - STD
      - SVC
      - SYP
      - SZL
      - THB
      - TJS
      - TMT
      - TND
      - TOP
      - TRY
      - TTD
      - TVD
      - TWD
      - TZS
      - UAH
      - UGX
      - USD
      - UYU
      - UZS
      - VEF
      - VND
      - VUV
      - WST
      - XAF
      - XCD
      - XDR
      - XOF
      - XPF
      - XTS
      - XXX
      - YER
      - ZAR
      - ZMW
      - ZWD
    dateOfBirth:
      pattern: "^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)$"
      type: string
      description: Date in the form YYYY-MM-DD.
    dfspList:
      type: object
      properties:
        id:
          type: integer
        prefix:
          type: integer
        fspId:
          type: string
        createdAt:
          type: string
          format: date-time
        status:
          type: string
        localeName:
          type: string
        dfspType:
          type: string
        additionalInfo:
          type: string
          nullable: true
        logoDataType:
          type: string
        logoBase64:
          type: string
          description: Base64-encoded logo image
        name:
          type: string

    errorResponse:
      type: object
      properties:
        statusCode:
          pattern: "^[1-9]\\d{2,3}$"
          type: string
          description: Error code as string.
        message:
          maxLength: 4096
          type: string
          description: Error message text.
        localeMessage:
          maxLength: 4096
          type: string
          description: Error message text.
        detailedDescription:
          maxLength: 10000
          type: string
          description: Error message text

    extensionItem:
      type: object
      properties:
        key:
          maxLength: 32
          minLength: 1
          type: string
        value:
          maxLength: 128
          minLength: 1
          type: string
    extensionList:

      type: array
      items:
        $ref: '#/components/schemas/extensionItem'

    fspId:
      maxLength: 32
      minLength: 1
      type: string
      description: FSP with which the party is associated.
    homeTransactionId:
      maxLength: 255
      type: string
      description: "Transaction ID from the DFSP backend, used to reconcile transactions between the Switch and the DFSP backend systems. In Mojaloop and PM4ML (SDK + Core Connector), this field is mandatory. However, most Core Banking Systems (CBS) generate the transaction ID only once the transaction stage is reached. Therefore, during the payer integration, the DFSP can provide a UUID in the initial call (e.g., KYC) and later override it with the actual transaction ID (homeTransactionId) in the subsequent transaction confirmation call."
    idSubValue:
      maxLength: 128
      minLength: 1
      type: string
      description: "Either a sub-identifier of an `{idValue}`, or a sub-type of the `{idType}`, normally a `{personalIdType}`, for example a phone number associated with an account"
    idType:
      type: string
      description: |-
        Below are the allowed values for the enumeration.
        - MSISDN -  An MSISDN (Mobile Station International Subscriber Directory Number, that is, the phone number) is used as reference to a participant. The MSISDN identifier should be in international format according to the [ITU-T E.164 standard](https://www.itu.int/rec/T-REC-E.164/en). Optionally, the MSISDN may be prefixed by a single plus sign, indicating the international prefix.
        - EMAIL - An email is used as reference to a participant. The format of the email should be according to the informational RFC 3696.
        - PERSONAL_ID - A personal identifier is used as reference to a participant. Examples of personal identification are passport number, birth certificate number, and national registration number. The identifier number is added in the PartyIdentifier element. The personal identifier type is added in the PartySubIdOrType element.
        - BUSINESS A specific Business (for example, an organization or a company) is used as reference to a participant. The BUSINESS identifier can be in any format. To make a transaction connected to a specific username or bill number in a Business, the PartySubIdOrType element should be used.
        - DEVICE A specific device (for example, a POS or ATM) ID connected to a specific business or organization is used as reference to a Party. For referencing a specific device under a specific business or organization, use the PartySubIdOrType element.
        - ACCOUNT_ID - A bank account number or FSP account ID should be used as reference to a participant. The ACCOUNT_ID identifier can be in any format, as formats can greatly differ depending on country and FSP.
        - IBAN A bank account number or FSP account ID is used as reference to a participant. The IBAN identifier can consist of up to 34 alphanumeric characters and should be entered without whitespace.
        - ALIAS An alias is used as reference to a participant. The alias should be created in the FSP as an alternative reference to an account owner. Another example of an alias is a username in the FSP system. The ALIAS identifier can be in any format. It is also possible to use the PartySubIdOrType element for identifying an account under an Alias defined by the PartyIdentifier.
      enum:
      - MSISDN
      - EMAIL
      - PERSONAL_ID
      - BUSINESS
      - DEVICE
      - ACCOUNT_ID
      - IBAN
      - ALIAS
    idValue:
      maxLength: 125
      minLength: 4
      pattern: "^[A-Za-z0-9]{4,125}$"
      type: string
      description: Identifier of the party.
    merchantClassificationCode:
      pattern: "^[\\d]{1,4}$"
      type: string
      description: "Up to 4 digits specifying the sender's merchant classification, if known and applicable."


    partyName:
      maxLength: 128
      minLength: 1
      type: string
    type:
      type: string
      description: |
        Below are the allowed values for the enumeration - CONSUMER Consumer is the initiator of the transaction. Example - peer-to-peer transfer or loan repayment from wallet. - AGENT Agent is the initiator of the transaction. Example - loan repayment via an agent. - BUSINESS Business is the initiator of the transaction. Example - loan disbursement. - DEVICE Device is the initiator of the transaction. Example - merchant-initiated merchant payment authorized on POS.
      enum:
      - CONSUMER
      - AGENT
      - BUSINESS
      - DEVICE
  
    subScenario:
      pattern: "^[A-Z_]{1,32}$"
      type: string
      example: "PERSON_TO_PERSON"
      description: "The subScenario field is mandatory and is used to specify the detailed transaction use case for each transfer. It enables differentiation between various transaction flows such as P2P (Person to Person), G2P (Government to Person), B2B (Business to Business), etc. The value must match the regex pattern ^[A-Z_]{1,32}$ and must be one of the allowed values listed below.
 
Allowed values:

  - PERSON_TO_PERSON: Person to Person transfer

  - PERSON_TO_BUSINESS: Payments from individual to business (e.g., merchant payment)

  - BUSINESS_TO_BUSINESS: Payments between two businesses

  - BUSINESS_TO_GOVERNMENT: Business paying to government (e.g., tax, license fees)

  - PERSON_TO_GOVERNMENT: Citizen paying to government (e.g., utility, tax, fees)

  - GOVERNMENT_TO_PERSON: Government disbursement (pensions, salaries, social payments)

  - BUSINESS_TO_PERSON: Salary, refunds, or other business-to-person payments

  - CROSS_BORDER_REMITTANCE: International remittance between countries (inbound or outbound)"
      
    supportedCurrencies:
      type: array
      description: A list of supported currency codes
      items:
        type: string
    initiatedTimestamp:
      pattern: "^(?:[1-9]\\d{3}-(?:(?:0[1-9]|1[0-2])-(?:0[1-9]|1\\d|2[0-8])|(?:0[13-9]|1[0-2])-(?:29|30)|(?:0[13578]|1[02])-31)|(?:[1-9]\\d(?:0[48]|[2468][048]|[13579][26])|(?:[2468][048]|[13579][26])00)-02-29)T(?:[01]\\d|2[0-3]):[0-5]\\d:[0-5]\\d(?:(\\.\\d{3}))(?:Z|[+-][01]\\d:[0-5]\\d)$"
      type: string
      description: An ISO-8601 formatted timestamp.

    TransactionScenario:

      type: string
      description: "Below are the allowed values for the enumeration. - TRANSFER - Used for performing a P2P (Peer to Peer, or Consumer to Consumer) transaction."
      example: TRANSFER
      enum:
      - TRANSFER
    AcceptPartyRequest:
      required:
      - acceptParty
      - amount
      type: object
      properties:
        acceptParty:
          type: boolean
          enum:
          - true
          - false
        amount:
          type: number
          description: A floating-point number (with the precision of `float` or `double`)
          format: double
        extensionList:
          $ref: '#/components/schemas/extensionList'
    acceptQuoteRequest:
      required:
      - acceptQuote
      type: object
      properties:
        homeTransactionId:
          $ref: '#/components/schemas/homeTransactionId'
        acceptQuote:
          type: boolean
          enum:
          - true
          - false
        extensionList:
          $ref: '#/components/schemas/extensionList'
    transferId:

      type: string
      description: A Mojaloop API transfer identifier (ULID).
    FspParty:
      required:
      - idType
      - idValue
      type: object
      properties:
        type:
          $ref: '#/components/schemas/type'
        idType:
          $ref: '#/components/schemas/idType'
        idValue:
          $ref: '#/components/schemas/idValue'
        idSubValue:
          $ref: '#/components/schemas/idSubValue'
        displayName:
          $ref: '#/components/schemas/partyName'
        firstName:
          $ref: '#/components/schemas/partyName'
        middleName:
          $ref: '#/components/schemas/partyName'
        lastName:
          $ref: '#/components/schemas/partyName'
        dateOfBirth:
          $ref: '#/components/schemas/dateOfBirth'
        merchantClassificationCode:
          $ref: '#/components/schemas/merchantClassificationCode'
        fspId:
          $ref: '#/components/schemas/fspId'
        extensionList:
          $ref: '#/components/schemas/extensionList'
    postSendMoneyRequest:
      required:
      - amount
      - amountType
      - currency
      - from
      - homeTransactionId
      - to
      - transactionType
      - subScenario
      type: object
      properties:
        homeTransactionId:
          $ref: '#/components/schemas/homeTransactionId'
        from:
          $ref: '#/components/schemas/FspParty'
        to:
          $ref: '#/components/schemas/FspParty'
        amountType:
          $ref: '#/components/schemas/amountType'
        currency:
          $ref: '#/components/schemas/currency'
        amount:
         $ref: '#/components/schemas/amount'
        transactionType:
          $ref: '#/components/schemas/TransactionScenario'
        subScenario:
          $ref: '#/components/schemas/subScenario'

        note:
          maxLength: 128
          type: string
    getDfspPrefixResponse:
      type: array
      items:
        $ref: '#/components/schemas/dfspList'

    getTransferResponse:
      type: object
      properties:
        transferId:
          $ref: '#/components/schemas/transferId'
        currentState:
          type: string
          example: "succeeded"
        direction:
          type: string
          enum:
          - OUTBOUND
        extensions:
          $ref: '#/components/schemas/extensionList'
        error:
          $ref: '#/components/schemas/errorResponse'
          
    postSendMoneyResponse:
      type: object
      properties:
        transferId:
          $ref: '#/components/schemas/transferId'
        homeTransactionId:
          $ref: '#/components/schemas/homeTransactionId'
        from:
          $ref: '#/components/schemas/FspParty'
        to:
          $ref: '#/components/schemas/FspParty'
        amountType:
          $ref: '#/components/schemas/amountType'
        transactionType:
          $ref: '#/components/schemas/TransactionScenario'
        note:
          maxLength: 128
          type: string
        amount:
          $ref: '#/components/schemas/amount'
        currency:
          $ref: '#/components/schemas/currency'
        currentState:
          $ref: '#/components/schemas/transferStatus'
          example: WAITING_FOR_PARTY_ACCEPTANCE
        initiatedTimestamp:
          $ref: '#/components/schemas/initiatedTimestamp'
        direction:
          type: string
          enum:
          - OUTBOUND
        supportedCurrencies:
          $ref: '#/components/schemas/supportedCurrencies'
        payeeFspFeeAmount:
          type: string
        subScenario:
          $ref: '#/components/schemas/subScenario'
        extensionList:
          $ref: '#/components/schemas/extensionList'
    transferStatus:
      type: string
      description: |
        Below are the allowed values for the enumeration - WAITING_FOR_PARTY_ACCEPTANCE An error has occurred during the transfer process.
        - WAITING_FOR_PARTY_ACCEPTANCE `AUTO_ACCEPT_PARTY` is set to "false" and party information has been returned, waiting to be accepted by the Payer DFSP using a `PUT /sendmoney/{transferId}` request.
        - WAITING_FOR_QUOTE_ACCEPTANCE `AUTO_ACCEPT_QUOTE` is set to "false" and quote information has been returned, waiting to be accepted by the Payer DFSP using a `PUT /sendmoney/{transferId}` request.
        - COMPLETED The transfer has completed successfully.
        - ABORTED The transfer has been ABORTED.
      enum:
      - WAITING_FOR_PARTY_ACCEPTANCE
      - WAITING_FOR_QUOTE_ACCEPTANCE
      - ABORTED
      - COMPLETED
      - ERROR_OCCURRED

    acceptPartyResponse:
      type: object
      properties:
        transferId:
          $ref: '#/components/schemas/transferId'
        homeTransactionId:
          $ref: '#/components/schemas/homeTransactionId'
        from:
          $ref: '#/components/schemas/FspParty'
        to:
          $ref: '#/components/schemas/FspParty'
        amountType:
          $ref: '#/components/schemas/amountType'
        transactionType:
          $ref: '#/components/schemas/TransactionScenario'
        note:
          maxLength: 128
          type: string
        amount:
          $ref: '#/components/schemas/amount'
        currency:
          $ref: '#/components/schemas/currency'
        currentState:
          type: string
          enum:
            - WAITING_FOR_QUOTE_ACCEPTANCE
            - ABORTED
            - COMPLETED
          example: WAITING_FOR_QUOTE_ACCEPTANCE
      
        initiatedTimestamp:
          $ref: '#/components/schemas/initiatedTimestamp'
        direction:
          type: string
          enum:
          - OUTBOUND
        supportedCurrencies:
          $ref: '#/components/schemas/supportedCurrencies'
        payeeFspFeeAmount:
          type: string
        subScenario:
          $ref: '#/components/schemas/subScenario'
        extensionList:
          $ref: '#/components/schemas/extensionList'

    acceptQuoteResponse:
      type: object
      properties:
        transferId:
          $ref: '#/components/schemas/transferId'
        homeTransactionId:
          $ref: '#/components/schemas/homeTransactionId'
        from:
          $ref: '#/components/schemas/FspParty'
        to:
          $ref: '#/components/schemas/FspParty'
        amountType:
          $ref: '#/components/schemas/amountType'
        transactionType:
          $ref: '#/components/schemas/TransactionScenario'
        note:
          maxLength: 128
          type: string
        amount:
          $ref: '#/components/schemas/amount'
        currency:
          $ref: '#/components/schemas/currency'
        currentState:
          type: string
          enum:
            - WAITING_FOR_QUOTE_ACCEPTANCE
            - ABORTED
            - COMPLETED
          example: COMPLETED
        initiatedTimestamp:
          $ref: '#/components/schemas/initiatedTimestamp'
        direction:
          type: string
          enum:
          - OUTBOUND
        supportedCurrencies:
          $ref: '#/components/schemas/supportedCurrencies'
        payeeFspFeeAmount:
          type: string
        subScenario:
          $ref: '#/components/schemas/subScenario'
        extensionList:
          $ref: '#/components/schemas/extensionList'

      
  responses:

    postSendMoneySuccess:
      description: Transfer completed successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/postSendMoneyResponse'
    acceptPartySuccess:
      description: Transfer completed successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/acceptPartyResponse'
            
    acceptQuoteSuccess:
      description: Transfer completed successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/acceptQuoteResponse' 
    getTransferSuccess:
      description: Transfer status retrieved successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/getTransferResponse'
    getDfspPrefixSuccess:
      description: Dfps prefix list retrieved successfully
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/getDfspPrefixResponse'

    getTransferError:
      description: An error occurred checking the transfer
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
          example:
            statusCode: "3208"
            message: Payment is not successful.Please try again later.
            localeMessage: Payment is not successful.Please try again later.
            detailedDescription: "Transfer ID not found"
    postTransferServerError:
      description: An error occurred processing the transfer
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
          example:
            statusCode: "3204"
            message: Payment is not successful. Please contact your service provider.
            localeMessage: Payment is not successful. Please contact your service provider.
            detailedDescription: |
              Got an error response resolving party: {
                errorInformation: {
                  errorCode: '3204',
                  errorDescription: 'Payment is not successful. Please contact your service provider.'
                }
              }
    putAcceptPartyTransferServerError:
      description: An error occurred processing the transfer
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
          example:
            statusCode: "3100"
            message: "Please try again later. If you still cannot do the payment, please contact your service provider."
            localeMessage: "Please try again later. If you still cannot do the payment, please contact your service provider."
            detailedDescription: "Got an error response requesting fxQuote: {\"errorInformation\":{\"errorCode\":\"3100\",\"errorDescription\":\"Generic validation error - Unsupported participant 'fxp'\"}}"
    putAcceptQuoteTransferServerError:
      description: An error occurred processing the transfer
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
          example:
            statusCode: "4001"
            message: Your service provider is not available for this service now. Please contact your service provider.
            localeMessage: Your service provider is not available for this service now. Please contact your service provider.
            detailedDescription: "Got an error response preparing transfer: {\n  errorInformation: { \n    errorCode: '4001', \n    errorDescription: 'Payer FSP insufficient liquidity' \n  }\n}\n"
  
    transferTimeout:
      description: An error occurred processing the request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/errorResponse'
          example:
            statusCode: "5000"
            message: "Please try again later. If you still cannot make the payment, please contact your service provider."
            localeMessage: "Please try again later. If you still cannot make the payment, please contact your service provider."
            detailedDescription: must NOT have fewer than 1 characters
  parameters:
    AuthorizationHeader:
      name: Authorization
      in: header
      description: "The `Authorization` header field is used by the API for securely transmitting information in a compact and self-contained manner as a JSON object. The field must be set with a JWT (JSON Web Token) generated using an RSA private key in PKCS#8 format, loaded from a specified file (e.g., private_key.pem), and signed with the RS256 algorithm. Using PKCS#8 format ensures that the private key is stored in a standardized and secure way. The payload must include the necessary claims required by the API. The secure JWT (JSON Web Token) generated from a private key and payload. Once generated, the JWT (the token) should be included in the Authorization header in the format Authorization: <JWT> to enable secure, authenticated API requests."
      required: true
      schema:
        type: string
        description: Bearer token for authorization
        example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9...
    idValue:
      name: idValue
      in: path
      description: Identifier of the party.
      required: true
      schema:
        maxLength: 128
        minLength: 1
        type: string
    idSubValue:
      name: idSubValue
      in: path
      description: Sub identifier of the party.
      required: true
      schema:
        maxLength: 128
        minLength: 1
        type: string
    transferId:
      name: transferId
      in: path
      description: Transfer identifier.
      required: true
      schema:
        pattern: "^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$"
        type: string
